apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: immich-recording-rules
  namespace: immich
spec:
  groups:
  - name: immich.recording
    interval: 1m
    rules:
    # Recording: Average upload queue size (5-minute window)
    - record: immich:upload_queue:avg5m
      expr: |
        avg_over_time(kubelet_volume_stats_used_bytes{persistentvolumeclaim="immich-upload"}[5m])
    
    # Recording: Upload rate (bytes/min)
    - record: immich:upload_rate:1m
      expr: |
        rate(kubelet_volume_stats_used_bytes{persistentvolumeclaim="immich-upload"}[1m])
    
    # Recording: SSD cache utilization
    - record: immich:ssd_cache:utilization
      expr: |
        (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"immich-cache|immich-upload"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"immich-cache|immich-upload"}) * 100
    
    # Recording: NAS library size
    - record: immich:nas_library:size
      expr: |
        kubelet_volume_stats_used_bytes{persistentvolumeclaim="immich-library"}
    
    # Recording: Database size
    - record: immich:database:size
      expr: |
        kubelet_volume_stats_used_bytes{persistentvolumeclaim="immich-db-primary"}
