# immich/redis.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-redis
    app.kubernetes.io/part-of: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          imagePullPolicy: IfNotPresent
          # No password by default for internal Immich setup
          # If you need a password, add args: ["--requirepass", "$(REDIS_PASSWORD)"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: immich-redis # References the pre-created PVC
---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
spec:
  selector:
    app.kubernetes.io/name: immich-redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  type: ClusterIP

