apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-db
  ports:
  - port: 5432
    name: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-db
  namespace: immich
spec:
  serviceName: immich-db
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      # Pin to SSD node (k3s-node1) for ReadWriteOnce PVC
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-node1

      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        
        env:
        - name: POSTGRES_DB
          value: immich
        - name: POSTGRES_USER
          value: immich
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-db-secret
              key: password
        - name: POSTGRES_INITDB_ARGS
          value: "-c shared_buffers=256MB -c effective_cache_size=1GB"
        
        volumeMounts:
        # Use PRE-CREATED PVCs from storage app
        - name: data
          mountPath: /var/lib/postgresql/data/pgdata
        - name: wal-archive
          mountPath: /wal-archive
        - name: config
          mountPath: /etc/postgresql
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U immich -d immich
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U immich -d immich
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      
      # ✅ FIXED: Reference pre-created PVCs (no volumeClaimTemplates)
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: immich-db-primary  # From storage app
      - name: wal-archive
        persistentVolumeClaim:
          claimName: immich-db-wal-archive  # From storage app
      - name: config
        configMap:
          name: postgresql-config
      - name: initdb
        emptyDir: {}

