apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-db
  ports:
  - port: 5432
    name: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-db
  namespace: immich
spec:
  serviceName: immich-db
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      # Pin to SSD node
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-node1

      securityContext:
        fsGroup: 999      # ✅ Chowns PVC to postgres group on mount
        runAsUser: 999
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch  

      initContainers:
      # ✅ ROOT INIT: Recursive chown/chmod (fixes CSI fsGroup issues)
      - name: volume-permissions
        image: busybox:1.36-glibc
        command:
        - sh
        - -c
        - |
          echo "Fixing /data permissions..."
          chown -R 999:999 /data
          find /data -type d -exec chmod 700 {} \;
          find /data -type f -exec chmod 600 {} \;
          
          # Fresh cluster: Clear if no PG_VERSION (safe for new PVC)
          if [ ! -f /data/PG_VERSION ]; then
            echo "Fresh PVC detected - clearing for initdb"
            rm -rf /data/*
          fi
          
          echo "Permissions fixed - PG_VERSION: $(ls /data/PG_VERSION 2>/dev/null || echo 'none')"
        securityContext:
          runAsUser: 0  # ✅ ROOT for chown
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests: {cpu: 10m, memory: 32Mi}

      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        
        env:
        - name: POSTGRES_DB
          value: immich
        - name: POSTGRES_USER
          value: immich
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-db-secret
              key: password
        
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: wal-archive
          mountPath: /wal-archive
        # ✅ DIRECT MOUNT: Config files to PGDATA (no init container needed)
        - name: postgresql-conf
          mountPath: /var/lib/postgresql/data/postgresql.conf
          subPath: postgresql.conf
        - name: pg-hba-conf
          mountPath: /var/lib/postgresql/data/pg_hba.conf
          subPath: pg_hba.conf
        
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U immich -d immich
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U immich -d immich
          initialDelaySeconds: 15
          periodSeconds: 5
        
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: immich-db-primary
      - name: wal-archive
        persistentVolumeClaim:
          claimName: immich-db-wal-archive
      # ✅ CONFIGMAP SUBPATH MOUNTS (direct to PGDATA)
      - name: postgresql-conf
        configMap:
          name: postgresql-config
          defaultMode: 0640
          items:
          - key: postgresql.conf
            path: postgresql.conf
      - name: pg-hba-conf
        configMap:
          name: postgresql-config
          defaultMode: 0600
          items:
          - key: pg_hba.conf
            path: pg_hba.conf

  # ✅ NO volumeClaimTemplates (using pre-created PVCs)

