apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-db
  ports:
  - port: 5432
    name: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-db
  namespace: immich
spec:
  serviceName: immich-db
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-node1

      initContainers:
      # ✅ NEW: Copy config files to PGDATA before initdb
      - name: config-setup
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          # Copy postgresql.conf to PGDATA
          cp /etc/postgresql/postgresql.conf /var/lib/postgresql/data/postgresql.conf
          
          # Copy pg_hba.conf to PGDATA
          cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
          
          # Fix permissions
          chown -R 999:999 /var/lib/postgresql/data
          chmod 600 /var/lib/postgresql/data/postgresql.conf
          chmod 600 /var/lib/postgresql/data/pg_hba.conf
          
          echo "Config files copied successfully"
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: config
          mountPath: /etc/postgresql
        securityContext:
          runAsUser: 999  # postgres UID
          runAsGroup: 999

      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres
        
        env:
        - name: POSTGRES_DB
          value: immich
        - name: POSTGRES_USER
          value: immich
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-db-secret
              key: password
        # ✅ REMOVED: Invalid POSTGRES_INITDB_ARGS
        
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: wal-archive
          mountPath: /wal-archive
        # Config now copied by init container to PGDATA
        
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U immich -d immich
          initialDelaySeconds: 60  # Increased for init container
          periodSeconds: 10
          timeoutSeconds: 5
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U immich -d immich
          initialDelaySeconds: 30
          periodSeconds: 5
        
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: immich-db-primary
      - name: wal-archive
        persistentVolumeClaim:
          claimName: immich-db-wal-archive
      - name: config
        configMap:
          name: postgresql-config
          items:
          - key: postgresql.conf
            path: postgresql.conf
          - key: pg_hba.conf
            path: pg_hba.conf
      securityContext:
        fsGroup: 999  # postgres GID
        runAsUser: 999

  # ✅ NO volumeClaimTemplates (using pre-created PVCs)

