apiVersion: v1
kind: Service
metadata:
  name: immich-db
  namespace: immich
spec:
  clusterIP: None
  selector:
    app: immich-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-db
  namespace: immich
spec:
  serviceName: immich-db
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-node1

      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch

      initContainers:
        - name: volume-permissions
          image: busybox:1.36-glibc
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -e
              echo "=== Setting up permissions ==="
              mkdir -p /data/pgdata
              chown -R 999:999 /data/pgdata
              chmod 700 /data/pgdata
              echo "=== Done ==="
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi

      containers:
        - name: postgresql
          image: ghcr.io/immich-app/postgres:15-vectorchord0.5.3
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 999
            runAsNonRoot: true

          ports:
            - name: postgres
              containerPort: 5432

          # Start Postgres directly with required preload libs for VectorChord.
          command: ["postgres"]
          args:
            - "-c"
            - "shared_preload_libraries=vectors.so,vchord.so"
            - "-c"
            - "search_path=$user,public,vectors"
            - "-c"
            - "logging_collector=on"
            - "-c"
            - "max_wal_size=2GB"
            - "-c"
            - "shared_buffers=512MB"
            - "-c"
            - "wal_compression=on"

          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_USER
              value: immich
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: password

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: wal-archive
              mountPath: /wal-archive
            - name: postgresql-conf
              mountPath: /etc/postgresql

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U immich -d immich
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U immich -d immich
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-db-primary
        - name: wal-archive
          persistentVolumeClaim:
            claimName: immich-db-wal-archive
        - name: postgresql-conf
          configMap:
            name: postgresql-config
            defaultMode: 0644

