apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-machine-learning
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-machine-learning
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-node1

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups: [109, 44] # 109 is 'render'and 44 is group ID

      containers:
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
          imagePullPolicy: IfNotPresent
          env:
            # ENABLE OPENVINO
            - name: ACCELERATORS
              value: "openvino"
            - name: MPLCONFIGDIR
              value: "/cache/matplotlib"
          envFrom:
            - configMapRef:
                name: immich-config
            - secretRef:
                name: immich-secret
          ports:
            - containerPort: 3003
              name: http
          volumeMounts:
            - name: model-cache
              mountPath: /cache
            - name: dev-dri
              mountPath: /dev/dri
      volumes:
        - name: model-cache
          emptyDir: {}  # or use a PVC if you want to persist downloaded models
        - name: dev-dri
          hostPath:
            path: /dev/dri

---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  selector:
    app.kubernetes.io/name: immich-machine-learning
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
