---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    JWT_SECRET: AgDdx6KM1i2GSRjnjkJF4Te47DnJxbQmNicUXWovpsvfq24pU59HyuoyQVT9JwXZzCcpTuzWr78HD6GrT1yqh4KBdNN6NKjkt1cU4Rau3e4RcdK91qgwJiAXanK0gUBmITtloGwe/aJ6fwz5PR5ZZ4lwe3S2WHHWwkxW2lDqFRbSPi6CfipTlSCOS++4L+MOZo7LUhALYTw0bLq8U31rcTzGs1VkOtEKB82V57qvxDbVvTHUU7SUhvG6FQV1aOBGfe9IAGXlk4OQznoemIgBpOpYtsMMlCYNtPLhI8SHXQ276vUUbSe7ilnzGSPQruqW9LTxliZlHKE6QTgmobX4NTFoilKlIyNIcWfJejy8Ymjin6D2OXdL0mMbq9VoNzExg0E/OKlgH/NjfCpJ+yXUABGM8t7KZb6roOhgBUjYBSwOgv3RbUrQOxgxdPB6MHoARM6F5OeZrZv+j/wx1bhUSGW44ZUMRyXqu/J70nTNf7CMKlgha8x/jsJ9l9OYu8+ur//hjKIH1ZJ5pmP12jwQ67a8uHmT8GHW4pA3xBdx9kL06dVMeeWXllXxZa54/JPxa4so6G0Wwr0L7cqhl7X1m5H4jstI2jRVJTWzDiutXgfJ8hKW5TfRjx7t1tV1MSAIDKITBTzx8iztZLToWA6aGyEYPjnp83EmhZbcYSiDE9ADq9ZEGDS/tki4Mbf7xwT9r24jcbtjgz2gFH51d80SypZLysRnU7dUPgQRUkiKQJz5mzOBUpvktGVMQfeYbtMzplRc1AAkq9kIEllj1A==
    api_key: AgDiaFmM/x/duMkl6pCUlv1koO/7KGz2IWniBOMy+d3VOr4d2EIT3jFM7Gp6wya3vLefJaeMZNTkLPUzqyuyrLaoZZVCfApFWHccGm6FJV5iKZ/GPNIxiDG8KdJAQfvlzxJPKXR9y/mflT9BvjOAE7nys5JfUe9po5p+gvygf/Bo0OICf5PZyM1g1rdPGcPLg44YhE8mM/k4jYV/AF96USPNaYrLZliUMdrYTUPGJAoRjPsclLib3pTmLv0BCG3dbZ0CIaVKtlHAdR//7OvqjvWybfyjYAfmEcoBgyBgCvnMTxcgxEtNQIGC2o08fw0OeNDMcOUxVkn0ZGOqpRwSzgu3a5Piab1yjucAtfXfm3AbiKxLXG1eFaSiHiBOMYoK075p+kFx79lMG6KpubhwJ6EQXbeaspKf+fm7tpesDXONUoAQqsXlvL+GCAMwuk8lQ1WWlOefshfKS15rub9eizdxJV4GAr4OfvLYDSl2A8wHOFq0wJG+VX8j3eGDp9YJ4sGL0tRwdSRFG/cvLBNvflN6lJES0zNAMbZdAdiQJON2qcrG0tpRtTNNdzjcuGVON1Ng4T8PbtUWotQVfxFYbulKaE5duFXptrTkJts1fuAdlWUjAszxthE22NOoBh2UuxfXjxGWSgwpDW9/XaKkcB4q4AnUpDzZXUsoXfnkPWzo17ciVAwVWNL/qQy0f51hbeUmWHQWwr2qt9WZR2l0R6lprK+3wbupfh+b8rrvaupXEM0tzwe2mlGN
  template:
    metadata:
      name: immich-secret
      namespace: immich
    type: Opaque
