---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    JWT_SECRET: AgDdx6KM1i2GSRjnjkJF4Te47DnJxbQmNicUXWovpsvfq24pU59HyuoyQVT9JwXZzCcpTuzWr78HD6GrT1yqh4KBdNN6NKjkt1cU4Rau3e4RcdK91qgwJiAXanK0gUBmITtloGwe/aJ6fwz5PR5ZZ4lwe3S2WHHWwkxW2lDqFRbSPi6CfipTlSCOS++4L+MOZo7LUhALYTw0bLq8U31rcTzGs1VkOtEKB82V57qvxDbVvTHUU7SUhvG6FQV1aOBGfe9IAGXlk4OQznoemIgBpOpYtsMMlCYNtPLhI8SHXQ276vUUbSe7ilnzGSPQruqW9LTxliZlHKE6QTgmobX4NTFoilKlIyNIcWfJejy8Ymjin6D2OXdL0mMbq9VoNzExg0E/OKlgH/NjfCpJ+yXUABGM8t7KZb6roOhgBUjYBSwOgv3RbUrQOxgxdPB6MHoARM6F5OeZrZv+j/wx1bhUSGW44ZUMRyXqu/J70nTNf7CMKlgha8x/jsJ9l9OYu8+ur//hjKIH1ZJ5pmP12jwQ67a8uHmT8GHW4pA3xBdx9kL06dVMeeWXllXxZa54/JPxa4so6G0Wwr0L7cqhl7X1m5H4jstI2jRVJTWzDiutXgfJ8hKW5TfRjx7t1tV1MSAIDKITBTzx8iztZLToWA6aGyEYPjnp83EmhZbcYSiDE9ADq9ZEGDS/tki4Mbf7xwT9r24jcbtjgz2gFH51d80SypZLysRnU7dUPgQRUkiKQJz5mzOBUpvktGVMQfeYbtMzplRc1AAkq9kIEllj1A==
    api_key: AgCxZidux58ZidP3ab45hSy3rXkAdMe4y/HV5rbGM8ACHjuzjopHIzWllS4M6aAccWbfEmTYtdBiEd1HMibZInPLI4Ua7cYgNxhYWR3PXKGteSZnUBp4mr082JmpGRM901HzMSAduZrfT1O1lyR/KX0yPqCSHfxxXllxQQYwPfxhlW4q2QmTHNd3V8nADoiNPfh0caso97q9BtL5gmqSTO1KQezsaBcD8KwFwO0V/2wMVnSHkPwVJhgV/bWhC+aVMXcTUxceCyog68HKSfaO0R51Mysq1afvax0eaXG5TjGm/HafsXx3x+EE2MaCVAq8kJZlhFjFr0xSU/lB9ySnsy5z3ISpTCXKw/+MeycVYrIURUn5fXIro2Zdkaw9lOXV+TonGoSQ9KpiB+LtjZ3VfEmLxMUXsaRvWD5fA2nLVIXB8DEX84waWwhw98d7/6we3gIki+xkUmxjcJvySbO/sd+RtlX4KuxZZPH1oCg/yvXjU8frkUT5r2d0tvAwpcBw8n1OvjC/HdSD2/LyTrYPU4+ipQ2qRFKYI2he3bEJkyOGMnEDh5aaVACck76ALVumi1NKIIGkepfiz98lXRYJ7t38KdDLdn3hFgRlkokBrx+wFR8ULFyz/iIWK5asf0ReZU4T5EEFTN0KtkGFdYFD2rr1E3jHh88xfZIHjIJek3ndBcXny33r6v71iIkr49syh2tQ8aNNJYmzDivDM8BAAz+D8khi3khDBoeduTUppn8QDL304EsR06vF
  template:
    metadata:
      name: immich-secret
      namespace: immich
    type: Opaque
