---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    JWT_SECRET: AgASUh5tBVkublFK65C5QiUp4EubZMM27mNXqUIzs2LPUFXMhZ4BfzWppRY5tvnbA/5dy8GbepZ1vRBd2WKuLfJr1d+WXpJOVhMekzXuOnUwePeqz3Lr4XAOyCM2x8oMIDLAh5dkud0az7yVQghP3qP3ysf0PqFyDtugzQlcGCMtc4RS5aCm9z2QI/h3g/DeHuqnmO3tOAbV25I9tyV207uQ6PRpA39vGDfOtXdxocHBdyz7oH1DDPfL3d5Ll5W8QANDe2ZKSoAnYF3jxXNwc8sxqsjjXKfTmQLF37GepbjWQjPpXWNwI2yYQw4T1d4b4EGvO7V7HJK2dWyYDRyGzuGrrIwqV5mWUzBoPCRVlt5WjAfq50usTNAO8YmhegYxJWGs/d2qRLGNV3Qdsg4OFWR/txqwneJNhS8PTLHATeTmGVYaAivAhUYtxSsxiZxdE9FHLa1bKaGPCC8wcdaFcWn0CRKhPblAfSliNbhG/DYf6F3VkZHApzRc7Lj4jNrOsVX3GenSuE51mIEZ4CBNnGpC68e/OlnLt1EfSOsUwqpLT+mryO6VW+Qu7rM6nydWUehZ5y5RrCyMkfyrRIt6lObaGsNO4dv66+tV+Ou+vz9wHoIym0zohMF9Zx9a6bvUuP7cpGkaBOiN9t3fipdhomIAr0OpKEDBqi7vjofFFOWtDNIq3Nr8t80N4Tedju5G1iySkuwXkNZasnN4faLzXizdsnQUjS7DpzWY+XA9B8trRMngyabUlDypLYY9D6VkpRGfMOo1h8tlF5OOsdBK9Cy0Yf0s2VnXj4MpYt3paSSxPufvjdvFT00RNA==
    api_key: AgBr5Zat7PNdTMBphKwblr6P4SGHNPsz+r2CUOyeWm+dgVIgtHzKHlbyKvk/lgGk/fI7kTFbk2dszRA1VKq/4yF1rTzltzERzTKR2np/0zfV9gFjnBQsqEzsVt8/3wO8evdGi++Ok50Co/doGPGWGq0iGcONoY0arI2eGIETZUsQlIdl++ypcg0OHI9Gp8lT0yAjXfLdou14pcllANbAuJ6FxCN+2b5/Rc7iamXs7cFeNZIJa4C2A0O6ej8s2WN/Y2mMYRCwzu0UvNuhFM3xFQc58KSQlFzr27A/+E/w4mruJJfddkaW6NJ3syVw68LMjS8f0760Q5a//yFi+pMkeSNigw7UM3/Nk6iP6JqmG/eGIJeK1NFNdXPnqAL/ZDQQNh26ARjZEWumBK8IPQj5deb7pGx1G7QIE05Tb6dcSK+YKyK7DqYc1G3kiyVtXo9SVnHjiO07J66BJaJ3yCDVrIYBAPzGxCSmpgIOns2zKoVq9pO2Y8y7L1rPKdB3HROHlmCvvtAumNo4VNJL17+Q+trhFDpBe7PEw+HIxHkFDKnpEU53uJTkyryodp4MHbRrONDNRn+vQpIcc9fB+Zu4qP7K4efw8MX0zCn+7BnYxXi7u+19dopAbHDnlFENzo5xzxfMXy9I06DsjJ0XXlszK+qGpv22e8VCqLuq38s/7Cm+cs/19rDh+02QnoIAM+N+dR6v0bNss9IjuF9m0ijBN3Ao3Bzm3tSe3J8/gEoX4CLThyBG7NqxG20t8M/z3A==
  template:
    metadata:
      name: immich-secret
      namespace: immich
    type: Opaque
