---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    JWT_SECRET: AgAhNn7m1HgBlkH5Si53JDy5+vitT38GKBdoueEzTY/EmJsduZxj/Gj0idH/yF0Z17o5e5OdPlGXSqXJwwf0mVee8AhmVRCzZsZVrj0C2LIsA//iPgWCFlSZHBgU7QMKnSzk3WZ1ykQtIdLsWBiMveIdzkzryRY3ictdYY6Cr7MSZFQEwA8LYbJOUSwq9EARS9/dTFtv21OQachlAo6/1J2Cbvd4iiGNPVtI3CoV1J+htW0fJv1z0hMOtZl084cBpCe0YSS5ik51e3Fx3FAjXBlIeu86xtqsrUAYDL8RiUkJ6hRfNNfJBS7wAoe8jtlta4dUre5FDRG+SLAzCNQVwKojAudh7mKPasLWNz8DmysSCLsVi92KByofqLBOH2JNLw8hp706iGSDDsXjCJ1MxnUBZzWg09U3Qml4cwB2uFZMHbI9WxvtuRdJ913HL9jueKUPctprjljs9MEcU1fWczvbvK7VYHE57erh39t/pnP8ds8lltaz1GghGgOd2Y9CE5SDu3saTHFA6zffH13SSIkX3/Gu02+JQPvFnodhoBYI8rt/HUP0vpB1HDD9IFiDlJC+Lthn+ETW9lT8FINxxOyO1FViwdr8hydJ5mtu3PzxBiRiDvLw8YDDZwgNHhB8E84svARlHnOAgT4NU7wxOrfxqUnf+E7gmSjiiowmKSnI/+blVCihCSj6yCv8feM/CebjK1Vyh2Uyaoh9Zn1teucOGE7CHr+nvIoPbyYtH2OtGxYWZyBNlvLPBz8Sz6aVSyfkVWWjELYs5lCOa2PMIoBnvNbd0fMVpIJV0ccAJOS6bkJURIom5Qlg
    api_key: AgBKzVo2BtLAO3EhhBvzZ2roeuyvTVw+9iDvoxLA/PomN/hxzooZZ6eASeDVCftHwtqjvJkos1WKgVsP2IUmzJGaqBzwoM1I3JWBJuhR1WdFz9dwCiR2woQZyvYoKPf3GNadWHqDEKR8x+wrJt5YFtocdYVYFnh06WG0ia6ZndutDnKBniF7CwgmQJK0c8Rb8EF3UHKbFXuIJQ85ZCDhmYOMNVs3JMXLal2/YAYgQXiHsHcOe2GabcRIl2/wygIKH9ahazY03bFsYTu+jyTtSA/7jqX5Hz3/7GMpnzo7D6KZr539X51bSXJq3LZyY+Ip5o9k4dTFohfIK7ZceYES4LjNJ+WutKOcQDYRxlvwwmlNrB6r5h4vSpd+v2oCA4Mll4Xk7SISc2RbGy9wvJic4j8PYQkHqWzBWG7saCHZy2ddiPwaVVsdSSyJoi+7MVtaSfZGdPbAyCnRxJfTYw9tbj7JjtuV1FD9lE5WDJPoTFZoPkstOruA1kYh9DZc+ivEVJN3wtzI/tXuqhwZKLo5TSvYlJrhsyH2NJURaiGJmt8c4UkrAT1nMDl//0dSbbze1nbEouM1LKFpRNvKwfZgShEDijzo+EcMk5nmSfK5mJM9v2Hl4sgwHu1RtNGe9MXejn13xmWXGOy3ErO23gsQkNaPdlROZidEalmoj9hhhjfutuX3dzqJlsT6bPViI8hlJAJ+mt02XmM5JPO7dvY2VDSc1Jyf5wvsYt8iWYMA6u3Gli6s6AOgmiVFdHz2Xg==
  template:
    metadata:
      name: immich-secret
      namespace: immich
    type: Opaque
