---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    JWT_SECRET: AgDdx6KM1i2GSRjnjkJF4Te47DnJxbQmNicUXWovpsvfq24pU59HyuoyQVT9JwXZzCcpTuzWr78HD6GrT1yqh4KBdNN6NKjkt1cU4Rau3e4RcdK91qgwJiAXanK0gUBmITtloGwe/aJ6fwz5PR5ZZ4lwe3S2WHHWwkxW2lDqFRbSPi6CfipTlSCOS++4L+MOZo7LUhALYTw0bLq8U31rcTzGs1VkOtEKB82V57qvxDbVvTHUU7SUhvG6FQV1aOBGfe9IAGXlk4OQznoemIgBpOpYtsMMlCYNtPLhI8SHXQ276vUUbSe7ilnzGSPQruqW9LTxliZlHKE6QTgmobX4NTFoilKlIyNIcWfJejy8Ymjin6D2OXdL0mMbq9VoNzExg0E/OKlgH/NjfCpJ+yXUABGM8t7KZb6roOhgBUjYBSwOgv3RbUrQOxgxdPB6MHoARM6F5OeZrZv+j/wx1bhUSGW44ZUMRyXqu/J70nTNf7CMKlgha8x/jsJ9l9OYu8+ur//hjKIH1ZJ5pmP12jwQ67a8uHmT8GHW4pA3xBdx9kL06dVMeeWXllXxZa54/JPxa4so6G0Wwr0L7cqhl7X1m5H4jstI2jRVJTWzDiutXgfJ8hKW5TfRjx7t1tV1MSAIDKITBTzx8iztZLToWA6aGyEYPjnp83EmhZbcYSiDE9ADq9ZEGDS/tki4Mbf7xwT9r24jcbtjgz2gFH51d80SypZLysRnU7dUPgQRUkiKQJz5mzOBUpvktGVMQfeYbtMzplRc1AAkq9kIEllj1A==
  template:
    metadata:
      name: immich-secret
      namespace: immich
    type: Opaque
