---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    JWT_SECRET: AgBjLMKw92e1JiSll3Z7Iwfa0w5auMzFfemAlzp9DoXSGTLuGiQr5xLaUYbiEkTn8tPNQWyGcecvw2rWkrdNAsboxWlJwyaMO+qla2FRB8MvJTRYSey+k3o/fjhCEEj0zQJv3UnsB490pU0oW5h6F/mwY4qsC8/rciIWnXFpsnVLcj0Sp3QUNoJhwWZq9IFtAD5E+h32QYNp3Daddj4mIfFQXClf1uDnP8dZCl2+Y++0A2wpTlKwedIwHHFo9Bg17i2dXqhLO6PzATy8uxyf1zAJ7CVbaEiwbLSaXXcBAGe383QOYZciaNhO48ZjH93FKVsWST32z4Auc48V/Va0eGjKNTopoMiEoj6RhAod02tOE8fmYOBzjBpqyNWrkBtAvMqXaglKY6QvfCqWJ0OPi2xotRUMle5ysQOd9Uu70nbyRwsuxgEHqu7KOeLXR/HktJ71oAA8Fil8IPtcdTvHOFrs7nMIX8dv64gtMjpr8c2v7I7Se/I1Xje0Z3k/xo8w/xmSKCNY6YPqapENfhgZ5XAmyIrWjGphkBvfPZtd1zKh6rNjwhxzogxqaE5Cw2yBJ3xt4aBs8pbaC/JcwAAVGlV8pKF0+pMs5ZnyBxS9zHemRSFfyKXiAfAe1Ozlr1RJFl9zlDY6RJA18Psr0H/VuYqEyo/+3f4R3JGtkHhsNr/oNfL/+JEIl+qwqDRli3v5g0FDcneXrWALsRejCQu032YTnpdGj9FlcYuzIeygI9Ze2a+1o9L1lFgWp5mhxna6u+Kl4tYmHpcNFjK7jA==
    api_key: AgCUpe3uJBwzLLpDIoNx5YpnJgorKypv0CP9B+YwlLykPUZP14t3FDhBOJlGLqte7JFQwa0jGDVuead9G3K6RjNJANqj8aQbdb7e2+HWiWJEhFaxHXXE6y/olyMTqJKGekK5DQFu0KMjy/56EAkuSvqvc3Q1X2+mPqE7zJsc6SNyPkJFspV2IXoRNs3aXuDzrGWWASt1gVwmkvPuparCIZEEgsATAwaQ050ZV4r91b/JGHX3dwh0UZFpAW3zoDS1FcvNLpeuTs5Y5fNs5vSIuMXDgKWgXFQWNv8/0Xl3bIPxnUqg3u2vrX8yM5vA5kXc5cCrhgy0UiStswdMGcV9zeZ2JiLP1kAcH+Bp8ASjltNWJ/P1u8TlbTJgnIRvP+1g+1Cgol9PfzdQIdPGnadOAr/1oOOHOwLxU/GASdUw+dwQXrkZP6Oj9sTlS+innSB3ongtwq1PPHbrFhSDY2svqW0ATS4HaPWkcSNB9E9D4flGuAZuNXjDljHiK5mbrAe3RBoB68dXmOQA3yvb8M4dSMzkIlINj2GvNccSr0kPVzGEAwrc0yf+aOvck08m+z5pAiSXnvfj688xTois/1tyPlc2zcGnLXySrsQE6sd/CZbrmMct34XogoqZjhT0J/k3VPD4D2imd8VbhmU+IvGtV4wIKaVdrZ/XP9R32ZRD9vpU1xmRpk6rw6s84+p+NU8wX6x9ZCIAx9ygbelgc2PQCBNSRje4oFPwHPDvughGuK8=
  template:
    metadata:
      name: immich-secret
      namespace: immich
    type: Opaque
