apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app.kubernetes.io/name: immich-server
  ports:
    - protocol: TCP
      port: 2283
      targetPort: 2283
