apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-rwx
  resources:
    requests:
      storage: 500Gi  # Adjust per your NAS capacity

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-thumbs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ssd-cache
  resources:
    requests:
      storage: 100Gi  # Typically 20-30% of library size

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-encoded-video
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ssd-cache
  resources:
    requests:
      storage: 150Gi  # Conservative; depends on transcoding depth

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-backups
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-rwx
  resources:
    requests:
      storage: 50Gi
